name: Build and Release KodiLogMonitor

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux
            arch: x64
          - os: windows-latest
            artifact_name: windows
            arch: x64
          - os: macos-14
            artifact_name: macos-arm64
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: ${{ (matrix.os == 'macos-14') && 'arm64' || 'x64' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyinstaller-hooks-contrib
        shell: bash

      - name: Build binary
        shell: bash
        run: |
          mkdir -p release
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            pyinstaller --noconsole --onefile \
                  --add-data "src/logo.ico;." \
                  --icon="src/logo.ico" \
                  --name "KodiLogMonitor" src/KodiLogMonitor.py
            mv dist/KodiLogMonitor.exe release/KodiLogMonitor-windows.exe

          elif [ "$RUNNER_OS" == "macOS" ]; then
            # On force l'architecture cible
            arch -${{ matrix.arch }} pyinstaller --noconsole --onefile \
                  --add-data "src/logo.png:." \
                  --icon="src/logo.icns" \
                  --name "KodiLogMonitor-${{ matrix.artifact_name }}" \
                  src/KodiLogMonitor.py
            mv dist/KodiLogMonitor-${{ matrix.artifact_name }} release/

          elif [ "$RUNNER_OS" == "Linux" ]; then
            pyinstaller --onefile src/KodiLogMonitor.py -n KodiLogMonitor
            mv dist/KodiLogMonitor release/KodiLogMonitor-linux
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kodi-log-monitor-${{ matrix.os }}
          path: release/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-releases
          pattern: kodi-log-monitor-*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # On cible tous les fichiers téléchargés dans le dossier
          files: all-releases/*
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
