name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # d√©clenche seulement sur les tags type v1.2.3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyinstaller-hooks-contrib

      - name: Build KodiLogMonitor binary
        run: |
          mkdir -p dist release
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile src/KodiLogMonitor.py -n KodiLogMonitor.exe
            cp dist/KodiLogMonitor.exe release/KodiLogMonitor-windows.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            pyinstaller --onefile src/KodiLogMonitor.py -n KodiLogMonitor
            cp -r dist/KodiLogMonitor release/KodiLogMonitor-macos
          elif [[ "${{ runner.os }}" == "Linux" ]]; then
            pyinstaller --onefile src/KodiLogMonitor.py -n KodiLogMonitor
            cp -r dist/KodiLogMonitor release/KodiLogMonitor-linux
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kodi-${{ github.ref_name }}-${{ runner.os }}-${{ github.run_id }}
          path: release/*
