name: Build and Release KodiLogMonitor

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyinstaller-hooks-contrib
        shell: bash

      - name: Clean previous builds
        shell: bash
        run: |
          rm -rf build
          rm -rf dist
          rm -rf release
          rm -rf __pycache__
          mkdir -p release
          
      - name: Build binary
        shell: bash
        run: |
          mkdir -p release

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          pyinstaller --noconsole --onefile \
                      --add-data "logo.ico;." \
                      --icon="logo.ico" \
                      --name "KodiLogMonitor" \
                      src/KodiLogMonitor.py
          cp dist/KodiLogMonitor.exe release/KodiLogMonitor-windows.exe
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          pyinstaller --noconsole --onefile \
                      --add-data "logo.png:." \
                      --icon="logo.icns" \
                      --name "KodiLogMonitor" \
                      src/KodiLogMonitor.py
          cp dist/KodiLogMonitor release/KodiLogMonitor-macos
        else
          pyinstaller --noconsole --onefile \
                      --add-data "logo.png:." \
                      --name "KodiLogMonitor" \
                      src/KodiLogMonitor.py
          cp dist/KodiLogMonitor release/KodiLogMonitor-linux
        fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kodi-log-monitor-${{ matrix.os }}
          path: release/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: kodi-log-monitor-ubuntu-latest
          path: release/ubuntu

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: kodi-log-monitor-macos-latest
          path: release/macos

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: kodi-log-monitor-windows-latest
          path: release/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release/**/* 
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
